apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbhgm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbhgm
  template:
    metadata:
      labels:
        app: nbhgm
    spec:
      containers:
      - image: okteto.dev/nbhgm:latest
        name: nbhgm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "98e8fc51-3125-4484-b06c-17746b02b5f8"
        - name: Vless_Path
          value: "/vl555768"
        - name: Vmess_UUID
          value: "98e8fc51-3125-4484-b06c-17746b02b5f8"
        - name: Vmess_Path
          value: "/vm6667478b"
        - name: Share_Path
          value: "/v2link"
